actors:
  hgc:
    image_url: /images/actors/alice.png
    name: hgc
    url: http://sns.example.com/alice
  akio:
    image_url: /images/actors/bob.png
    name: Akio
    url: http://sns.example.com/bob
  moriyuka:
    image_url: /images/actors/bob.png
    name: Moriyuka
    url: http://sns.example.com/bob
author: hgc
description: NEWPEACE Inc.の社内勉強会の様子や学びを、メンバーがポップに、赤裸々にお届けします。
description_long: NEWPEACE Inc.の社内勉強会の様子や学びを、メンバーがポップに、赤裸々にお届けします。コミュニティを中心に、実践的な内容から理論・アイデアまで勝手気ままに話しています．
email: info@newpeace.jp
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: newpeace
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: N.L.C (NEWPEACE LEARNING CLUB)
url: http://newpeace.jp
